version: '3.2'
services:
  ruuvi-collector:
    image: ruuvi-collector:latest
    privileged: true
    restart: unless-stopped
    volumes:
      - "./ruuvi-collector.properties:/app/target/ruuvi-collector.properties"
      - "./ruuvi-names.properties:/app/target/ruuvi-names.properties"
    network_mode: "host"
  influxdb:
    image: influxdb:1.4.2
    ports:
      - "8086:8086"
    volumes:    
      - influxdb_data:/var/lib/influxdb:rw
    restart: unless-stopped
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_DB=${INFLUX_DB}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}

  grafana:
    image: fg2it/grafana-armhf:v5.1.4
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  influxdb_data:
  grafana_data:
